name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" > keystore.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD }}" --batch keystore.jks.asc > keystore.jks
          echo "ext {" >> keystore.gradle
          echo "RELEASE_STORE_FILE = \"../keystore.jks\"" >> keystore.gradle
          echo "RELEASE_STORE_PASSWORD = \"${{ secrets.KEYSTORE_PASSWORD }}\"" >> keystore.gradle
          echo "RELEASE_KEY_ALIAS = \"${{ secrets.KEY_ALIAS }}\"" >> keystore.gradle
          echo "RELEASE_KEY_PASSWORD = \"${{ secrets.KEY_PASSWORD }}\"" >> keystore.gradle
          echo "}" >> keystore.gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run unit tests
        run: ./gradlew test